spring:
  devtools:
    livereload:
      enabled: true
  datasource:
    url: jdbc:mysql://localhost:3306/idus?useSSL=false&useUnicode=true&serverTimezone=Asia/Seoul&allowPublicKeyRetrieval=true
    username: root
    password: rootpassword
  jpa:
    show-sql: true
    database-platform: org.hibernate.dialect.MySQL8Dialect
    hibernate:
      ddl-auto: validate
  mvc:
    pathmatch:
      matching-strategy: ant_path_matcher # swagger-ui 오류 수정
server:
  port: 8080

app:
  application:
    security:
      secret: donghyun
      expiration: 6048000000
